### ISSUE TITLE
cleanup `recursiveModuleBundle` method

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#340]
Because of the `v1beta1.concentratedliquidity` module, we had to enable `experimentalGlobalProtoNamespace` option: 
 https://github.com/osmosis-labs/osmojs/blob/59d389d695ea9325310dc014a52ef314bc3e55b0/packages/osmojs/scripts/codegen.js#L21

Ideally, we can see what the source of this issue is, maybe rebuilding the tool that creates the objects to be better.

**Comment by Zetazzz** [comment]
Done by the PR linked

**Comment by RonCan** [comment]
concentratedliquidity is still not available on the osmosis object. Is this linked PR supposed to fix that? It doesn't seem to.
